apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: db_h
      valueFrom:
        configMapKeyRef:
          name: db-connection
          key: db_h.txt
    - name: db_p
      valueFrom:
        configMapKeyRef:
          name: db-connection
          key: db_p.txt
