apiVersion: v1
kind: Service
metadata:
  name: excer1-service
  namespace: webapp

spec:
  selector:
    app: nginx

  ports:
   - protocol: TCP
     port: 80
     targetPort: 80

  type: LoadBalancer
