apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  namespace: webapp

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/logs

---

apiversion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-log
  namespace: webapp
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
