apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-01-deployment
  namespace: webapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: log-volume
          mountPath: /var/log/nginx
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: log-volume
        persistentVolumeClaim:
          claimName: pvc-log
